/**
 * Post-build script: reads dist/index.html and writes it to
 * packages/computer-hosts/src/gui/app.html for the Worker to serve.
 */
const src = new URL("../dist/index.html", import.meta.url);
const htmlDest = new URL(
  "../../computer-hosts/src/gui/app.html",
  import.meta.url,
);
const moduleDest = new URL(
  "../../computer-hosts/src/gui/assets.generated.ts",
  import.meta.url,
);

const html = await Deno.readTextFile(src);
await Deno.writeTextFile(htmlDest, html);
await Deno.writeTextFile(
  moduleDest,
  [
    "// Generated by packages/dashboard/scripts/emit-assets.ts.",
    "export const appHtml =",
    `  ${JSON.stringify(html)};`,
    "",
  ].join("\n"),
);
console.log(`Wrote ${htmlDest.pathname} (${html.length} bytes)`);
console.log(`Wrote ${moduleDest.pathname}`);
